import registration from "../page/registrationPage"

describe('ensek energy corp Registration', () => {
  beforeEach ( () => {
    registration.openUrl()
    registration.clickRegistrationButton()
  })
  it('EK001_registration with valid credentials', () => {
    registration.enterEmailAddress("test@gmail.com")
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2023")
    registration.clickRegisterButton()
    registration.verifyUserRegistration()
    registration.verifyRegistrationPageDisplay()
  })
  it('EK002_registration with invalid email', () => {
    registration.enterEmailAddress("testAbc")
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2023")
    registration.clickRegisterButton()
    registration.verifyInvalidEmailMessage()
  })
  it('EK003_registration with email contains special character', () => {
    registration.enterEmailAddress("test%%@gmail.com")
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2023")
    registration.clickRegisterButton()
    registration.verifyInvalidEmailMessage()
    registration.verifyRegistrationPageDisplay()
  })
  it('EK004_registration with email contains space', () => {
    registration.enterEmailAddress("test er@gmail.com")
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2023")
    registration.clickRegisterButton()
    registration.verifyInvalidEmailMessage()
  })
  it('EK005_registration without entering email', () => {
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2023")
    registration.clickRegisterButton()
    registration.verifyEmailIsRequiredMessage()
  })
  it('EK006_registration with six char password', () => {
    registration.enterEmailAddress("tester@gmail.com")
    registration.enterPassword("Te@202")
    registration.enterConfirmPassword("Te@202")
    registration.clickRegisterButton()
    registration.verifyUserNotAbleToRegisterwithSixCharPassword()
  })
  it('EK007_registration without using uppercase in password', () => {
    registration.enterEmailAddress("tester@gmail.com")
    registration.enterPassword("tester@2023")
    registration.enterConfirmPassword("tester@2023")
    registration.clickRegisterButton()
    registration.verifyUpperCaseErrormessage()
  })
  it('EK008_registration without using lowercase in password', () => {
    registration.enterEmailAddress("tester@gmail.com")
    registration.enterPassword("TESTER@2023")
    registration.enterConfirmPassword("TESTER@2023")
    registration.clickRegisterButton()
    registration.verifyLowerCaseErrormessage()
  })
  it('EK009_registration without using number or special character in password', () => {
    registration.enterEmailAddress("tester@gmail.com")
    registration.enterPassword("TesterCyp")
    registration.enterConfirmPassword("TesterCyp")
    registration.clickRegisterButton()
    registration.verifyNumberOrSpecialCharacterErrormessage()
  })
  it('EK0010_registration with different value in password and confirm password', () => {
    registration.enterEmailAddress("tester@gmail.com")
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2022")
    registration.clickRegisterButton()
    registration.verifyPasswordMisMatchErrormessage()
  })
  it('EK0011_register without entering mandatory fields', () => {
    registration.clickRegisterButton()
    registration.verifyRequiredErrormessage()
  })
  it('EK0012_register without entering password', () => {
    registration.enterEmailAddress("tester@gmail.com")
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2022")
    registration.clickRegisterButton()
    registration.verifyPasswordRequiredErrormessage()
  })
  it('EK0013_register without entering confirm password', () => {
    registration.enterEmailAddress("tester@gmail.com")
    registration.enterPassword("Tester@2023")
    registration.enterConfirmPassword("Tester@2022")
    registration.clickRegisterButton()
    registration.verifyPasswordMisMatchErrormessage()
  })
})